# Tópico 01 - Aula 02

In [3]:
import numpy as np

#np.random.randint(menorValor,maiorValor,proporção da tabela)
np.random.randint(1,10,[2,2])
#array([[7, 1],[8, 5]])

np.random.rand(2,2)
#array([[0.87193794, 0.49075618],[0.82258484, 0.70771006]])



array([[0.87193794, 0.49075618],
       [0.82258484, 0.70771006]])